#!name=自定义列表  
[Rule]
DOMAIN-SUFFIX,bangumi.tv,DIRECT
DOMAIN-SUFFIX,bgm.tv,DIRECT
#DOMAIN-SUFFIX,jetbrains.com,DIRECT
DOMAIN-SUFFIX,deepl.com,DIRECT
DOMAIN-SUFFIX,mangafuna.xyz,PROXY

#bing
DOMAIN-SUFFIX,bing.com,DIRECT
DOMAIN-SUFFIX,bing.net,DIRECT
DOMAIN-SUFFIX,bingads.com,DIRECT
DOMAIN-SUFFIX,bingagencyawards.com,DIRECT
DOMAIN-SUFFIX,bingapistatistics.com,DIRECT
DOMAIN-SUFFIX,bingsandbox.com,DIRECT
DOMAIN-SUFFIX,bingvisualsearch.com,DIRECT
DOMAIN-SUFFIX,bingworld.com,DIRECT

#Postman
DOMAIN-SUFFIX,postman.com,DIRECT
DOMAIN-SUFFIX,getpostman.com,DIRECT

DOMAIN-SUFFIX,umeng.com,REJECT
